### ISSUE TITLE
Escaped quotes in string breaks syntax highlighting

### ISSUE THREAD

**Issue by ItsFrankieD** [kaermorchen/twig-language-server#31]
There's an issue with escaped quotes inside strings. Note the escaped single-quote in the following `trim()` call.

```twig
{% set teaser = node.field_teaser is not empty
  ? node.field_teaser.value
  : node.body.value|striptags|replace({ '&nbsp;': ' ' })[:165]|trim(".,?!-–—:;\"' ", 'right') ~ '...'
%}
```

This causes the rest of the document up to another single quote to be read as a string.

Both single and double quotes cause this issue.

See the attached screenshot for a visual on the issue.

Thanks!

![Screenshot 2023-10-17 131807](https://github.com/kaermorchen/twig-language-server/assets/38739027/dd4fd16b-68ae-4ad7-834b-eab9ca6b3e51)

**Comment by kaermorchen** [comment]
> Discussion continued in #32.
