### ISSUE TITLE
CRITICAL - All functionality broken in release v0.5.1

### ISSUE THREAD

**Issue by ItsFrankieD** [kaermorchen/twig-language-server#34]
I've just updated the Modern Twig extension, and all functionality has completely broken for me.

I have reinstalled and reloaded VS Code multiple times to no avail. Rolling back to v0.5.0 fixes the issue.

![image](https://github.com/kaermorchen/twig-language-server/assets/38739027/1e0d3f1c-34b0-41a3-abf8-a4961da1956b)

**Comment by kaermorchen** [comment]
Hi.

Looks like TLS hadn't been started. If you have big project, it can take some time.

**Comment by ItsFrankieD** [comment]
It seems that was the case. Strange, I'd given it upwards of 10 minutes to load with no project present. I replicated this on multiple machines, as well.

Upon testing again today post-update, it seems to be working fine. This still may an issue worth looking into given it was reproducible on multiple machines.

Thanks much!

**Comment by ItsFrankieD** [comment]
Well, irony has it out for me. As soon as I marked as closed, the issue reoccurred. It seems to once again be broken.

**Comment by kaermorchen** [comment]
Did you see some errors in the twig-language-server channel?

**Comment by ItsFrankieD** [comment]
Oddly enough, the TLS channel is empty for both versions 0.5.0 and 0.5.1.

I believe this is where I should be checking?

![image](https://github.com/kaermorchen/twig-language-server/assets/38739027/21d0e5ee-e96f-4fa2-a6c0-83ccb65aeac1)

**Comment by ItsFrankieD** [comment]
Are there any updates regarding this issue?

**Comment by kaermorchen** [comment]
I am sorry, I don't have time for Open Source at least until December. Main job takes me all

**Comment by ItsFrankieD** [comment]
No worries! Thanks for the response.

**Comment by ItsFrankieD** [comment]
Closing—project assumed abandoned.
