### ISSUE TITLE
Support for named arguments

### ISSUE THREAD

**Issue by Zekfad** [kaermorchen/twig-language-server#42]
> Named arguments for macros and dot operator arguments were added in Twig 3.15.

https://twig.symfony.com/doc/3.x/templates.html#named-arguments

![image](https://github.com/user-attachments/assets/8d6590a9-1330-48fe-a013-419b17cda8b2)

Is there any plans to add support for named arguments?

**Comment by kaermorchen** [comment]
Hi.

I will add support it but it will not be a fast
